package com.nagpal.bala.playgroundapp.effectivejava.item88;

import java.io.*;
import java.util.Date;

public class ValidateByteStreamAfterDeserialization {

    /*
            Following byte stream is generated by removing checks in period class, creating the following invalid object and serializing
            it to byte stream

            Period incorrectValue = new Period(new Date(2023, 11, 25, 10, 10), new Date(2023, 10, 25,10,10)) ;
     */

    private static final byte[] invalidPeriod = {
            -84, -19, 0, 5, 115, 114, 0, 57, 99, 111, 109, 46, 110, 97, 103, 112, 97, 108, 46, 98,
            97, 108, 97, 46, 112, 108, 97, 121, 103, 114, 111, 117, 110, 100, 97, 112, 112, 46, 101, 102, 102, 101, 99, 116, 105, 118, 101,
            106, 97, 118, 97, 46, 105, 116, 101, 109, 56, 56, 46, 80, 101, 114, 105, 111, 100, 61, 77, 127, -89, 4, -73, 103, 44, 2,
            0, 2, 76, 0, 3, 101, 110, 100, 116, 0, 16, 76, 106, 97, 118, 97, 47, 117, 116, 105, 108, 47, 68, 97, 116, 101, 59, 76,
            0, 5, 115, 116, 97, 114, 116, 113, 0, 126, 0, 1, 120, 112, 115, 114, 0, 14, 106, 97, 118, 97, 46, 117, 116, 105, 108,
            46, 68, 97, 116, 101, 104, 106, -127, 1, 75, 89, 116, 25, 3, 0, 0, 120, 112, 119, 8, 0, 0, 56, 20, 28, -90, -31, 0,
            120, 115, 113, 0, 126, 0, 3, 119, 8, 0, 0, 56, 20, -73, 37, -87, 0, 120
    };

    /*
        Period class overrides read object method and validates the object.


     */
    public static void main(String[] args) throws Exception {
//        Period incorrectValue = new Period(new Date(2023, 11, 25, 10, 10), new Date(2023, 10, 25,10,10)) ;
//        serialize(incorrectValue);
        Period p = (Period) deserialize(invalidPeriod);
        System.out.println(p);
    }

    // Returns the object with the specified serialized form
    private static Object deserialize(byte[] sf) {
        try {
            ObjectInputStream ois = new ObjectInputStream(new ByteArrayInputStream(sf));
            ois.registerValidation(new ObjectGraphValidator(), 0);
            return ois.readObject();
        } catch (IOException | ClassNotFoundException e) {
            throw new IllegalArgumentException(e);
        }
    }

    private static void serialize(Period period) throws  Exception {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        ObjectOutputStream oos = new ObjectOutputStream(outputStream);
        oos.writeObject(period);

        outputStream.toByteArray();
    }
}
