#example how to configure map in application.yml
clientSecrets:
  123-456-789: ${VAL1}
  231-456-789: bca-def-ghi
  321-456-789: cab-def-ghi

#path where uploaded files will be saved.
fileUploadPath: "/Users/bnagpal1/temp"

#spring config
spring:
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB
  datasource:
    url: jdbc:postgresql://localhost:5432/playground
    username: postgres
    password: password
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        # required for fixing: no currentsessioncontext configured!
        current_session_context_class: thread

management:
  endpoints:
    web:
      exposure:
        include: "loggers,health,info"

  loggers:
    enabled: true

#pulsar
pulsarURL: pulsar://standalone:6650
#pulsarURL: pulsar://localhost:6650

#logging:
#  level:
#    org.zalando.logbook: TRACE

#logbook:
#  obfuscate:
#    headers:
#      - Authorization
#      - X-Secret
#      - user-agent
#    parameters:
#      - access_token
#      - password
#  write:
#    chunk-size: 1000
