apiVersion: apps/v1
kind: Deployment
metadata:
  name: bala-app
  namespace: dev02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bala-app
  template:
    metadata:
      labels:
        app: bala-app
        version: v9
    spec:
      containers:
      - name: bala-app
        image: odxbootstrapacr94a636d0.azurecr.io/odx/bala_app:v9
        resources:
#          limits:
#            cpu: 500m
#            memory: 256m
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: log4j
            mountPath: /home/bala/config
            readOnly: false  
      volumes:
        - name: log4j
          configMap:
            name: log4j-config
